@Library('mylibrary') _
pipeline
{
    agent any
    stages
    {
        stage('download')
        {
            steps
            {
                script
                {
                    cicd.gitdownload("maven")
                }
            }
        }
        stage('build')
        {
            steps
            {
                script
                {
                    cicd.buildArtifact()
                }
            }
        }
        stage('deploy')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("declarativepipelinewithsharedlibrary","172.31.19.226","testapp")
                }
            }
        }
        stage('testing')
        {
            steps
            {
                script
                {
                    cicd.gitdownload("Functionaltesting")
                    cicd.runselenium("declarativepipelinewithsharedlibrary")
                }
            }
        }
        stage('delivery')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("declarativepipelinewithsharedlibrary","172.31.16.176","prodapp")
                }
            }
        }
    }
}
